-- INSERT INTO team (name, description, creation_date, last_modification_date) VALUES
-- ('Team Mobile', 'Team for mobile projects', NOW(), NOW()),
-- ('Team Java', 'Team for java projects', NOW(), NOW()),
-- ('Team Magento', 'Team for magento projects', NOW(), NOW()),
-- ('Team Angular', 'Team for angular projects', NOW(), NOW());
--
-- INSERT INTO role (name, description, creation_date, last_modification_date) VALUES
-- ('Team leader', 'Leader of the team', NOW(), NOW()),
-- ('Delivery manager', 'Takes care of product delivery', NOW(), NOW()),
-- ('Scrum master', 'Overview of agile ceremonies', NOW(), NOW()),
-- ('Product owner', 'Owns the product', NOW(), NOW()),
-- ('No role', 'This user has no role', NOW(), NOW());
--
-- INSERT INTO employee_position (name, description, creation_date, last_modification_date) VALUES
-- ('Fullstack developer', 'Backend + Frontend developer', NOW(), NOW()),
-- ('Backend developer', 'Writes code for backend', NOW(), NOW()),
-- ('Frontend developer', 'Writes code for frontend', NOW(), NOW()),
-- ('HR employee', 'Works in HR department', NOW(), NOW());
--
-- INSERT INTO project (name, description, creation_date, last_modification_date) VALUES
-- ('NXTHR-company', 'Company copy from sage', NOW(), NOW()),
-- ('NXTHR-assets', 'Assets copy from sage', NOW(), NOW()),
-- ('Calvin', 'Consors bank project', NOW(), NOW()),
-- ('EFE', 'Employee frontend project', NOW(), NOW()),
-- ('NXT-plug', 'Mobile app for ,car charging', NOW(), NOW());
--
-- INSERT INTO account_extra_column (title, creation_date, last_modification_date) VALUES
-- ('IBAN eur', NOW(), NOW()),
-- ('IBAN ron', NOW(), NOW()),
-- ('Type of contract', NOW(), NOW());
--
-- INSERT INTO employee_details (start_date, employee_position_id, manager_id, seniority_level, creation_date, last_modification_date) VALUES
-- ( NOW(), 1, NULL, 'INTERN', NOW(), NOW()),
-- ( NOW(), 2, 1, 'JUNIOR_DEVELOPER', NOW(), NOW()),
-- ( NOW(), 3, 2, 'MID_DEVELOPER', NOW(), NOW()),
-- ( NOW(), 4, 3, 'SENIOR_DEVELOPER', NOW(), NOW());
--
-- INSERT INTO account (first_name, last_name,work_email, password, auth_role, tshirt, location, creation_date, last_modification_date, employee_id, photo_URL) VALUES
-- ('Radu', 'Marinau','email1@example.com','password1','ADMIN', 'M', 'Cluj', NOW(), NOW(), 1, 'https://media.istockphoto.com/id/1150528651/photo/successful-it-developer.jpg?b=1&s=612x612&w=0&k=20&c=sizKCRrpGQgYdIBBczZnuKQbBKEEmyTxoFKApGd3HBs='),
-- ('Ionut', 'Baias','email2@example.com','password2','NORMAL_USER', 'S', 'Sibiu', NOW(), NOW(), 2, 'https://media.istockphoto.com/id/1150528651/photo/successful-it-developer.jpg?b=1&s=612x612&w=0&k=20&c=sizKCRrpGQgYdIBBczZnuKQbBKEEmyTxoFKApGd3HBs='),
-- ('Razvan', 'Joita','email3@example.com','password3','NORMAL_USER', 'M', 'Oradea', NOW(), NOW(), 3, 'https://media.istockphoto.com/id/1150528651/photo/successful-it-developer.jpg?b=1&s=612x612&w=0&k=20&c=sizKCRrpGQgYdIBBczZnuKQbBKEEmyTxoFKApGd3HBs='),
-- ('Mircea', 'Ilina','email4@example.com','password4','ADMIN', 'S', 'Valcea', NOW(), NOW(), 4, 'https://media.istockphoto.com/id/1150528651/photo/successful-it-developer.jpg?b=1&s=612x612&w=0&k=20&c=sizKCRrpGQgYdIBBczZnuKQbBKEEmyTxoFKApGd3HBs=');
--
-- INSERT INTO account_extra_details (account_id, input_value, title, creation_date, last_modification_date) VALUES
-- (1, 'RO49AAAA1B31007593840000', 'IBAN ron', NOW(), NOW()),
-- (1, 'EN49AAXX1B31007593840000', 'IBAN eur', NOW(), NOW()),
-- (3, 'DE49AAAA1B31007593840000', 'IBAN ron', NOW(), NOW()),
-- (4, 'AG49AAAA1B31007593840000', 'IBAN eur', NOW(), NOW());
--
-- INSERT INTO employee_details_role (employee_id, role_id, creation_date, last_modification_date) VALUES
-- (1, 5, NOW(), NOW()),
-- (2, 2, NOW(), NOW()),
-- (3, 3, NOW(), NOW());
--
-- INSERT INTO employee_details_extra_details (employee_id, input_value, title, creation_date, last_modification_date) VALUES
-- (1, 'Employee', 'Type of contract', NOW(), NOW()),
-- (2, 'SRL', 'Type of contract', NOW(), NOW()),
-- (3, 'PFA', 'Type of contract', NOW(), NOW()),
-- (4, 'Employee', 'Type of contract', NOW(), NOW());
--
-- INSERT INTO employee_details_team (team_id, employee_id, creation_date, last_modification_date) VALUES
-- (2, 1, NOW(), NOW()),
-- (1, 2, NOW(), NOW()),
-- (1, 3, NOW(), NOW()),
-- (3, 4, NOW(), NOW());
--
-- INSERT INTO team_project (team_id, project_id, creation_date, last_modification_date) VALUES
-- (2, 1, NOW(), NOW()),
-- (2, 2, NOW(), NOW()),
-- (2, 3, NOW(), NOW()),
-- (4, 4, NOW(), NOW()),
-- (1, 5, NOW(), NOW());
--
-- INSERT INTO team_project_position (team_id, project_id, employee_position_id, creation_date, last_modification_date) VALUES
-- (2, 1, 1, NOW(), NOW()),
-- (2, 2, 2, NOW(), NOW()),
-- (2, 3, 4, NOW(), NOW()),
-- (4, 4, 3, NOW(), NOW());
--
-- INSERT INTO employee_role_team_project_position (team_id, project_id, employee_position_id ,employee_id, role_id, creation_date, last_modification_date) VALUES
-- --(2, 1, 1, 2, 2),
-- --(2, 3, 4, 3, 3),
-- (2, 2, 2, 1, 5, NOW(), NOW()),
-- (2, 1, 1, 2, 2, NOW(), NOW());
--
--
--
--
--
--
-- -- Example data for the assets table
-- INSERT INTO assets (name, category, description, creation_date, last_modification_date)
-- VALUES
--     ('Dell XPS 13', 'LAPTOP', 'Ultra-thin laptop for professionals', NOW(), NOW()),
--     ('Logitech MX Master 3', 'MOUSE', 'High-performance wireless mouse', NOW(), NOW()),
--     ('Corsair K95 RGB Platinum', 'KEYBOARD', 'Mechanical gaming keyboard', NOW(), NOW()),
--     ('Sony WH-1000XM4', 'HEADPHONES', 'Noise-canceling over-ear headphones', NOW(), NOW());
--
-- -- Example data for the extra_info table
-- INSERT INTO assets_extra_column (info_title, description, creation_date, last_modification_date)
-- VALUES
--     ('Serial Number', 'Asset serial number', NOW(), NOW()),
--     ('Purchase Date', 'Date of asset purchase', NOW(), NOW()),
--     ('Warranty Expires', 'Warranty expiration date', NOW(), NOW());
--
-- -- Example data for the asset_extra_info table
-- INSERT INTO asset_extra_info (info_title, asset_id, value_info, creation_date, last_modification_date)
-- VALUES
--     ('Serial Number', 1, '12345', NOW(), NOW()),
--     ('Purchase Date', 2, '2023-01-15', NOW(), NOW()),
--     ('Warranty Expires', 3, '2024-05-20', NOW(), NOW());
--
-- -- Example data for the user_asset table
-- INSERT INTO account_asset (employee_id, asset_id, date_given, creation_date, last_modification_date)
-- VALUES
--     (1, 1, '2023-02-10 08:00:00', NOW(), NOW()),
--     (2, 3, '2023-03-20 14:30:00', NOW(), NOW()),
--     (3, 2, '2023-04-05 10:15:00', NOW(), NOW());
--
-- -- Example data for the user_asset_extra_info table
-- INSERT INTO account_asset_extra_info (account_asset_id, info_title, value_info, creation_date, last_modification_date)
-- VALUES
--     (1, 'Serial Number', '54321', NOW(), NOW()),
--     (1, 'Purchase Date', '2023-02-05', NOW(), NOW()),
--     (2, 'Serial Number', '67890', NOW(), NOW()),
--     (3, 'Purchase Date', '2023-03-18', NOW(), NOW());
--
--
