package nexttech.mapper;

import nexttech.domain.dto.employeeRoleTeamProjectPositionDto.AddEmployeeRoleTeamProjectPositionRequestDto;
import nexttech.domain.dto.employeeRoleTeamProjectPositionDto.AddEmployeeRoleTeamProjectPositionResponseDto;
import nexttech.domain.dto.employeeRoleTeamProjectPositionDto.GetEmployeeRoleTeamProjectPositionRequestDto;
import nexttech.domain.dto.employeeRoleTeamProjectPositionDto.GetEmployeeRoleTeamProjectPositionResponseDto;
import nexttech.domain.dto.employeeRoleTeamProjectPositionDto.UpdateEmployeeRoleTeamProjectPositionRequestDto;
import nexttech.domain.dto.employeeRoleTeamProjectPositionDto.UpdateEmployeeRoleTeamProjectPositionResponseDto;
import nexttech.domain.model.entities.EmployeeRoleTeamProjectPosition;
import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
public interface IEmployeeRoleTeamProjectPositionMapper {

    EmployeeRoleTeamProjectPosition addEmployeeRoleTeamProjectPositionRequestDtoToEmployeeRoleTeamProjectPosition(AddEmployeeRoleTeamProjectPositionRequestDto employeeRoleTeamProjectPosition);

    EmployeeRoleTeamProjectPosition getEmployeeRoleTeamProjectPositionRequestDtoToEmployeeRoleTeamProjectPosition(GetEmployeeRoleTeamProjectPositionRequestDto employeeRoleTeamProjectPosition);

    EmployeeRoleTeamProjectPosition updateEmployeeRoleTeamProjectPositionRequestDtoToEmployeeRoleTeamProjectPosition(UpdateEmployeeRoleTeamProjectPositionRequestDto employeeRoleTeamProjectPosition);

    AddEmployeeRoleTeamProjectPositionResponseDto employeeRoleTeamProjectPositionToAddEmployeeRoleTeamProjectPositionResponseDto(EmployeeRoleTeamProjectPosition employeeRoleTeamProjectPosition);

    GetEmployeeRoleTeamProjectPositionResponseDto employeeRoleTeamProjectPositionToGetEmployeeRoleTeamProjectPositionResponseDto(EmployeeRoleTeamProjectPosition employeeRoleTeamProjectPosition);

    UpdateEmployeeRoleTeamProjectPositionResponseDto employeeRoleTeamProjectPositionToUpdateEmployeeRoleTeamProjectPositionResponseDto(EmployeeRoleTeamProjectPosition employeeRoleTeamProjectPosition);

}
