package nexttech.mapper;

import nexttech.domain.dto.employeeDetailsExtraDetailsDto.AddEmployeeDetailsExtraDetailsRequestDto;
import nexttech.domain.dto.employeeDetailsExtraDetailsDto.AddEmployeeDetailsExtraDetailsResponseDto;
import nexttech.domain.dto.employeeDetailsExtraDetailsDto.GetEmployeeDetailsExtraDetailsRequestDto;
import nexttech.domain.dto.employeeDetailsExtraDetailsDto.GetEmployeeDetailsExtraDetailsResponseDto;
import nexttech.domain.dto.employeeDetailsExtraDetailsDto.UpdateEmployeeDetailsExtraDetailsRequestDto;
import nexttech.domain.dto.employeeDetailsExtraDetailsDto.UpdateEmployeeDetailsExtraDetailsResponseDto;
import nexttech.domain.model.entities.EmployeeDetailsExtraDetails;
import org.mapstruct.Mapper;

@Mapper(componentModel = "spring", uses = {IAccountExtraColumnMapper.class, IEmployeeDetailsMapper.class})
public interface IEmployeeDetailsExtraDetailsMapper {

    EmployeeDetailsExtraDetails addEmployeeDetailsExtraDetailsRequestDtoToEmployeeDetailsExtraDetails(AddEmployeeDetailsExtraDetailsRequestDto employeeDetailsExtraDetails);

    EmployeeDetailsExtraDetails getEmployeeDetailsExtraDetailsRequestDtoToEmployeeDetailsExtraDetails(GetEmployeeDetailsExtraDetailsRequestDto employeeDetailsExtraDetails);

    EmployeeDetailsExtraDetails updateEmployeeDetailsExtraDetailsRequestDtoToEmployeeDetailsExtraDetails(UpdateEmployeeDetailsExtraDetailsRequestDto employeeDetailsExtraDetails);

    AddEmployeeDetailsExtraDetailsResponseDto employeeDetailsExtraDetailsToAddEmployeeDetailsExtraDetailsResponseDto(EmployeeDetailsExtraDetails employeeDetailsExtraDetails);

    GetEmployeeDetailsExtraDetailsResponseDto employeeDetailsExtraDetailsToGetEmployeeDetailsExtraDetailsResponseDto(EmployeeDetailsExtraDetails employeeDetailsExtraDetails);

    UpdateEmployeeDetailsExtraDetailsResponseDto employeeDetailsExtraDetailsToUpdateEmployeeDetailsExtraDetailsResponseDto(EmployeeDetailsExtraDetails employeeDetailsExtraDetails);

}
